### ISSUE TITLE
detailed description

### ISSUE THREAD

**Issue by GuobinZhangTJU** [melodist/MELTNET#1]
nice work, which database you used for train? can you share your processing order or references ? thanks for your help~waiting for you~

**Comment by melodist** [comment]
Thank you for your attention.
Database used for training is clinical PET/CT images.
Sorry for not having summary of my process.
I'll summarize my process later after my tight schedule.
There is a reference you can get a help.

T. Moriya et al., “Unsupervised segmentation of 3D medical images based on clustering and deep representation learning,” 2018, p. 71.
http://dx.doi.org/10.1117/12.2293414

**Comment by GuobinZhangTJU** [comment]
got it ~~many thanks~~~
